[project]
name = "project-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiodns>=3.5.0",
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.13",
    "httpx>=0.28.1",
    "pip>=25.1.1",
]
